# Gradle CircleCI configuration
# See https://circleci.com/docs/2.0/language-java/ for more details
version: 2
jobs:
  build:
    docker:
      - image: cimg/openjdk:26.0

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle.kts" }}
          - v1-dependencies-

      - run: ./gradlew --no-daemon dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle.kts" }}

      - run: ./gradlew --no-daemon build

      - store_test_results:
          path: build/reports/tests
