name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug Report] Title Here "
labels: []
assignees: []
body:
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Please provide a clear and concise description of what the bug is.
      placeholder: The bug is...
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Provide steps you can take to reliably reproduce this bug
      placeholder: |
        1.
        2.
        3.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Result
      description: What did you expect to happen when this bug occurred?
      placeholder: I expected...
    validations:
      required: true
  - type: textarea
    id: debug
    attributes:
      label: Debug Output
      description: Please run the `debug` command and paste it here or upload it as an attachment. If you cannot run the command, please provide information about your system such as operating system version, ShiverFork version, etc.
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: Additional Info
      description: Any additional info that you think might be useful or relevant to this bug
  - type: checkboxes
    id: checks
    attributes:
      label: Checklist
      description: Before submitting your issue, please affirm the following
      options:
        - label: I have looked for information about this [within the documentation](https://jmusicbot.com/)
          required: true
        - label: I have searched for similar issues [on the issues page](https://github.com/lilliepad1/MusicBotShiverFork/issues?q=is%3Aissue)
          required: true
        - label: I am using the latest ShiverFork release from [the releases page](https://github.com/lilliepad1/MusicBotShiverFork/releases)
          required: true
  - type: input
    id: version
    attributes:
      label: ShiverFork Version
      description: Which version of ShiverFork are you running?
    validations:
      required: true
