name: Feature Request
description: Suggest an idea for this project
title: "[Feature Request] Title Here"
labels: []
assignees: []
body:
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: Please provide a clear and concise description of what the problem is.
      placeholder: A common problem users face is...
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: What is your ideal solution to the problem?
      description: Describe a clear and concise description of what you want to happen.
      placeholder: My solution to the above problem is...
    validations:
      required: true
  - type: textarea
    id: procedure
    attributes:
      label: How would this feature be used?
      description: Describe the basic flow/steps of using this feature.
      placeholder: |
        1.
        2.
        3.
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: Additional Info
      description: Any additional info that you think might be useful or relevant to this feature request
  - type: checkboxes
    id: checks
    attributes:
      label: Checklist
      description: Before submitting your issue, please affirm the following
      options:
        - label: I have checked [the documentation](https://jmusicbot.com/) to make sure this feature doesn't already exist
          required: true
        - label: I have searched for [similar feature requests](https://github.com/jagrosh/MusicBot/labels/enhancement)
          required: true
        - label: I have confirmed that my requests is **not** on the [list of things that will not be added](https://jmusicbot.com/things-that-wont-be-added)
          required: true
        - label: "I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)"
          required: true
